"""Add chat_type_favorites table

Revision ID: 2a3c0d4f5709
Revises: e6b4cb3c0892
Create Date: 2026-04-08 07:50:34.563460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3c0d4f5709'
down_revision: Union[str, Sequence[str], None] = 'e6b4cb3c0892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_type_favorites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chat_type_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_type_id'], ['chat_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chat_type_id', name='uq_user_chat_type_favorite')
    )
    op.create_index(op.f('ix_chat_type_favorites_chat_type_id'), 'chat_type_favorites', ['chat_type_id'], unique=False)
    op.create_index(op.f('ix_chat_type_favorites_id'), 'chat_type_favorites', ['id'], unique=False)
    op.create_index(op.f('ix_chat_type_favorites_user_id'), 'chat_type_favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_type_favorites_user_id'), table_name='chat_type_favorites')
    op.drop_index(op.f('ix_chat_type_favorites_id'), table_name='chat_type_favorites')
    op.drop_index(op.f('ix_chat_type_favorites_chat_type_id'), table_name='chat_type_favorites')
    op.drop_table('chat_type_favorites')
    # ### end Alembic commands ###
