"""add autogenerated chat title bool

Revision ID: e6b4cb3c0892
Revises: 7b677b5054b2
Create Date: 2026-04-07 14:42:03.721285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b4cb3c0892'
down_revision: Union[str, Sequence[str], None] = '7b677b5054b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('title_auto_generated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'title_auto_generated')
    # ### end Alembic commands ###
