from pydantic import BaseModel
from typing import List

class RAGQuery(BaseModel):
    """
    Represents a single query to be used in the RAG pipeline.
    """
    text: str

class RAGQueries(BaseModel):
    """
    Represents a list of queries generated by the query expansion engine.
    """
    queries: List[RAGQuery]
